export interface LeaderboardEntry {
  rank: number;
  name: string;
  username: string;
  points: number;
  contributions: number;
  projects: string[];
}

export const leaderboardData: LeaderboardEntry[] = [
  {
    rank: 1,
    name: "Yuvaranjan S",
    username: "hipstarVenom ",
    points: 300,
    contributions: 9,
    projects: ["CSE C Website", ""],
  },
  {
    rank: 2,
    name: "Tarun Kumar",
    username: "--",
    points: 200,
    contributions: 7,
    projects: ["CSE C Website", ""],
  },
  {
    rank: 3,
    name: "SHAAM SUNDER V",
    username: "--",
    points: 100,
    contributions: 1,
    projects: ["LIght Yagami Portfolio"],
  },
  {
    rank: 4,
    name: "Sanjai .M",
    username: "--",
    points: 70,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 5,
    name: "R SHARVESH",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["ASCII", ""],
  },
  {
    rank: 6,
    name: "R.SHREENIDHI",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["CSE C Section Class Website"],
  },
  {
    rank: 7,
    name: "Vasanth. K",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["CSE C Section Class Website"],
  },
  {
    rank: 8,
    name: "Vishaal G",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 9,
    name: "Nithin Athithya",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 10,
    name: "Sanjeth S",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["LIght Yagami Portfolio"],
  },
  {
    rank: 11,
    name: "Thamilarasan S",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 12,
    name: "R Tharun Jeevan",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 13,
    name: "Yogesh",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 14,
    name: "Saranya",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
  {
    rank: 15,
    name: "Tanish M",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["CSE C Section Class Website"],
  },
  {
    rank: 16,
    name: "Sarath Chandran",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["FocusFlow"],
  },
  {
    rank: 17,
    name: "Thirunavukarasu",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["LIght Yagami Portfolio"],
  },
  {
    rank: 18,
    name: "Swetha P",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["LIght Yagami Portfolio"],
  },
  {
    rank: 19,
    name: "Sidarth",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["ASCII", ""],
  },
  {
    rank: 20,
    name: "Tarun Kumar",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["CSE C Section Class Website"],
  },
  {
    rank: 21,
    name: "SUNJANA MANASSVI V P",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["CSE C Section Class Website"],
  },
  {
    rank: 22,
    name: "Srisurya",
    username: "--",
    points: 50,
    contributions: 1,
    projects: ["Typing Speed Tester"],
  },
];
